[cursor.style]
shape = "Block"

[debug]
log_level = "Warn"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations_theme_variant = "None"
opacity = 1

[window.padding]
x = 0
y = 0

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

[terminal]
