#!/bin/sh

path=$(pwd)

ln -sf $path/.zshrc $HOME/.zshrc
ln -sf $path/.zshenv $HOME/.zshenv
ln -sf $path/.tmux.conf $HOME/.tmux.conf
ln -sf $path/.Xresources $HOME/.Xresources
ln -sf $path/.zprofile $HOME/.zprofile

# User bin folder
[ ! -d $HOME/bin ] && mkdir -p $HOME/bin
ln -sf $path/bin/usd $HOME/bin/usd
ln -sf $path/bin/eur $HOME/bin/eur
ln -sf $path/bin/btc $HOME/bin/btc
ln -sf $path/bin/myip $HOME/bin/myip

# Config directory
[ ! -d $HOME/.config ] && mkdir $HOME/.config

[ -d $HOME/.config/alacritty ] && rm -rf $HOME/.config/alacritty
ln -sf $path/config/alacritty $HOME/.config/alacritty

[ -d $HOME/.config/dunst ] && rm -rf $HOME/.config/dunst
ln -sf $path/config/dunst $HOME/.config/dunst

[ -d $HOME/.config/htop ] && rm -rf $HOME/.config/htop
ln -sf $path/config/htop $HOME/.config/htop

[ -d $HOME/.config/httpx ] && rm -rf $HOME/.config/httpx
ln -sf $path/config/httpx $HOME/.config/httpx

[ -d $HOME/.config/i3 ] && rm -rf $HOME/.config/i3
ln -sf $path/config/i3 $HOME/.config/i3

[ -d $HOME/.config/lf ] && rm -rf $HOME/.config/lf
ln -sf $path/config/lf $HOME/.config/lf

[ -d $HOME/.config/mako ] && rm -rf $HOME/.config/mako
ln -sf $path/config/mako $HOME/.config/mako

[ -d $HOME/.config/nvim ] && rm -rf $HOME/.config/nvim
ln -sf $path/config/nvim $HOME/.config/nvim

[ -d $HOME/.config/rofi ] && rm -rf $HOME/.config/rofi
ln -sf $path/config/rofi $HOME/.config/rofi

[ -d $HOME/.config/sway ] && rm -rf $HOME/.config/sway
ln -sf $path/config/sway $HOME/.config/sway

[ -d $HOME/.config/waybar ] && rm -rf $HOME/.config/waybar
ln -sf $path/config/waybar $HOME/.config/waybar

[ -d $HOME/.config/polybar ] && rm -rf $HOME/.config/polybar
ln -sf $path/config/polybar $HOME/.config/polybar

[ -d $HOME/.config/wofi ] && rm -rf $HOME/.config/wofi
ln -sf $path/config/wofi $HOME/.config/wofi

# Local directory
[ ! -d $HOME/.local ] && mkdir -p $HOME/.local/share
[ ! -d $HOME/.local/share ] && mkdir $HOME/.local/share
