require("nvim-treesitter.configs").setup {
    ensure_installed = {
        "c",
        "cpp",
        "html",
        "javascript",
        "typescript",
        "json",
        "yaml",
        "toml",
        "markdown",
        "bash",
        "python",
        "go",
        "bp",
        "rust",
        "zig",
        "java",
        "cmake",
        "make",
        "css",
        "csv",
        "diff",
        "dockerfile",
        "gitcommit",
        "gitignore",
        "gomod",
        "gosum",
        "sql",
        "htmldjango",
        "kotlin",
        "lua",
        "nginx",
        "php",
        "proto",
        "ssh_config",
        "tsx",
        "twig",
        "vim",
        "vue",
    },
    sync_install = false,
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
}
